# Generated by Django 3.1 on 2023-07-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_aluno_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='celular',
            field=models.CharField(default='', max_length=13),
        ),
    ]
